### ISSUE TITLE
Swift 3 and Swift 4 support?

### ISSUE THREAD

**Issue by explicitcall** [nodekit-io/nodekit-darwin-lite#6]
Hi, this project looks very interesting, but can't be compiled with Xcode 8 and Xcode 9, are there any plans to support this? 
Thanks

**Comment by guycreate** [comment]
Yes, should be on the roadmap for this fall.    Definitely required by several of us.    Of course pull requests welcome, but this one not too far away as we should never be more than one major release behind and with Swift 4 become 2 releases behind.

**Comment by patgoley** [comment]
Hey @explicitcall, the project has been updated to Swift 4 / Xcode 9. Just point to the 0.9.1 release in your Podfile. Let me know if you have any issues!
